### ISSUE TITLE
Add Config Variables to GraphQL Service Model

### ISSUE THREAD

**Issue by m4dcoder** [harness/harness-go-sdk#110]
Request to add config variables to the GraphQL service model @ https://github.com/harness/harness-go-sdk/blob/main/harness/cd/graphql/model_service.go#L5. We look up service by name and so we have to call GetServiceByName and then use ConfigAsCode GetServiceById to be able to get the list of ConfigVariables.

Also, there are multiple API calls behind the scene here. 1) GetServiceByName has to list services by application and then loop thru to find the service by name.  2) ConfigAsCode GetServiceById has to get the directory tree, recursive calls to find object, and then make another API call to get service. Will there be performance issue once we have many services under an app?

**Comment by micahlmartin** [comment]
@m4dcoder unfortunately, the problem is that the ConfigVariables aren't available through the GraphQL API. The only option then is to go the ConfigAsCode API route. Also, because of the way these API's work, traversing the tree is less than ideal but it's our only option. As far as performance goes, it's traversing the directory in memory so at least it's not repeatedly calling the API. I've tested this with pretty large amount of objects so it shouldn't break. I would be interested to see if you started running into issues.
